version: '3'
services:
  dev:
    image: tyba-backend
    build: .
    ports:
      - "8080:8080"
    restart: always
    environment:
      - 'spring.datasource.url=jdbc:postgresql://postgres:5432/tyba_backend'
    depends_on:
      - redis
      - postgres
    volumes:
      - kotlinvolume:/var/lib/kotlin
    networks:
      - kotlinnetwork
      - postgresnetwork
      - redisnetwork
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - redisnetwork
  postgres:
    image: 'postgres:latest'
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
      - './src/main/resources/migration/V1.1__create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql'
    environment:
      - POSTGRES_PASSWORD=adminadmin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tyba_backend
    ports:
      - '5432:5432'
    networks:
      - postgresnetwork
volumes:
  postgres-data:
  kotlinvolume:

networks:
  kotlinnetwork:
  postgresnetwork:
  redisnetwork:
